# Activation de la console Web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Connexion JDBC H2 (Mode fichier au lieu de la mémoire RAM)
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Conservation des tables créées par Hibernate
spring.jpa.hibernate.ddl-auto=update

# Afficher les requêtes SQL dans la console
spring.jpa.show-sql=true
